# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.require_version ">= 1.6.0"

boxes = [
    {
        :name => "nginx",
        :mem => "2048",
        :cpu => "1",
        :ip => "192.168.66.110"
    },
    {
        :name => "tomcat1",
        :mem => "2048",
        :cpu => "1",
        :ip => "192.168.66.111"
    },
    {
        :name => "tomcat2",
        :mem => "2048",
        :cpu => "1",
        :ip => "192.168.66.112"
    }
]

Vagrant.configure(2) do |config|

	config.vm.box = "jeqo/oracle-jdk-8-centos7"
  config.vm.box_version = "8.66.20160116222952"
  boxes.each do |opts|
      config.vm.define opts[:name] do |config|
        config.vm.hostname = opts[:name]
        config.vm.provider "vmware_fusion" do |v|
          v.vmx["memsize"] = opts[:mem]
          v.vmx["numvcpus"] = opts[:cpu]
        end

        config.vm.provider "virtualbox" do |v|
          v.customize ["modifyvm", :id, "--memory", opts[:mem]]
          v.customize ["modifyvm", :id, "--cpus", opts[:cpu]]
        end
        config.vm.network :private_network, auto_config: true, ip: opts[:ip], bridge:"ens1f0", bootproto: "static", gateway: "192.168.66.1"
      end
  end

end